name: Unite Build and Release

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.short }}
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sha
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build for ${{ matrix.arch }}
        run: |
          GOARCH=${{ matrix.arch }} go build -o unite-workload-example-${{ matrix.arch }} cmd/main.go

      - name: Prepare unite.yml
        run: |
          export PLATFORM=${{ matrix.arch }}
          export GITHUB_RELEASE_VERSION=${{ github.sha }}
          envsubst < .unite.yml.template > unite.yml

      - name: Prepare RELEASE.md
        run: |
          export PLATFORM=${{ matrix.arch }}
          export GITHUB_RELEASE_VERSION=${{ github.sha }}
          export DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          envsubst < RELEASE.md.template > RELEASE.md

      - name: List files for debugging
        run: ls -la

      - name: Create zip archive
        run: |
          zip -j unite-workload-example-${{ matrix.arch }}-${{ steps.sha.outputs.short }}.zip unite-workload-example-${{ matrix.arch }} unite.yml RELEASE.md

      - name: Upload zip archive
        uses: actions/upload-artifact@v3
        with:
          name: unite-workload-example-${{ matrix.arch }}-${{ steps.sha.outputs.short }}.zip
          path: unite-workload-example-${{ matrix.arch }}-${{ steps.sha.outputs.short }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download zip archive for amd64
        uses: actions/download-artifact@v3
        with:
          name: unite-workload-example-amd64-${{ needs.build.outputs.sha }}.zip
          path: ./build
      - name: Download zip archive for arm64
        uses: actions/download-artifact@v3
        with:
          name: unite-workload-example-arm64-${{ needs.build.outputs.sha }}.zip
          path: ./build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.build.outputs.sha }}
          release_name: Release ${{ needs.build.outputs.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Assets for amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/unite-workload-example-amd64-${{ needs.build.outputs.sha }}.zip
          asset_name: unite-workload-example-amd64-${{ needs.build.outputs.sha }}.zip
          asset_content_type: application/zip

      - name: Upload Release Assets for arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/unite-workload-example-arm64-${{ needs.build.outputs.sha }}.zip
          asset_name: unite-workload-example-arm64-${{ needs.build.outputs.sha }}.zip
          asset_content_type: application/zip